### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by FontEndArt** [azl397985856/zhuque-client#1]
如果考虑维护的话，想提出一些问题...

1.是否考虑增加一些功能
增加 unhandledrejection 来处理Promise reject的一些错误
统计线上 console 相关消息， 如 warning、error之类
统计 socket 的一些错误，比如意外断开之类的
2.是否只关注错误？有考虑增加手动埋点相关想法吗？
用于一些特殊业务场景，比如：订单前后、手动上报特殊错误等

3.是否考虑为其他开发者提供扩展方法，如 mixin、extend 之类？

**Comment by azl397985856** [comment]
1. unhandledrejection 可以考虑。 eg
```js
window.addEventListener('unhandledrejection', event => ···);
```

console等不统计，只统计性能和错误。     console属于排查问题相关的额外信息，用户可以选择上报，不做自动处理

socket等错误属于网络层面，也属于错误，会考虑。

2. 这个属于用户行为分析，链路分析相关。 同样和排查问题相关，可以考虑加，这方面做的比较好的是logrocket

3. 框架定制的东西如果想做的完善肯定要加，主流的监控方案都有的，不过这一块想做的完善，我个人建议还要做相应的调试工作，因此工作量不小的

**Comment by FontEndArt** [comment]
考虑将这个项目完善吗？  还是说排期很靠后  /手动笑哭😂

**Comment by azl397985856** [comment]
> 考虑将这个项目完善吗？ 还是说排期很靠后 /手动笑哭😂

哈哈。 看破不说破，我们还是friends

**Comment by FontEndArt** [comment]
好嘞，我还是去看看手写react吧  看起来这个排期比较靠前
